# Generated by Django 5.1.11 on 2025-06-12 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='color',
            new_name='title_color',
        ),
    ]
